name: Build and Deploy Docker Image to Amazon ECR and Fargate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev/prod'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::140561047603:role/github-action-role
          aws-region: eu-west-2
      - name: Authenticate with ECR
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 140561047603.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker Image
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker build -t packagebuildert:$TIMESTAMP .

      - name: Tag Docker Image
        run: |
          TIMESTAMP=$(aws ecr list-images --repository-name packagebuildert --region eu-west-2 --filter tagStatus=UNTAGGED --query 'imageIds[*].imageTag' --output text)
          if [ -z "$TIMESTAMP" ]; then
            LATEST_TAG="latest"
          else
            LATEST_TAG=$(echo $TIMESTAMP | tr ' ' '\n' | sort -nr | head -n 1)
          fi
          REPO_URL="140561047603.dkr.ecr.eu-west-2.amazonaws.com"
          docker tag packagebuildert:$LATEST_TAG $REPO_URL/packagebuildert:$TIMESTAMP
          docker tag packagebuildert:$TIMESTAMP $REPO_URL/packagebuildert:latest

      # - name: Tag Docker Image
      #   run: |
      #     docker tag packagebuildert:$TIMESTAMP 140561047603.dkr.ecr.eu-west-2.amazonaws.com/packagebuildert:$TIMESTAMP

      - name: Push Docker Image
        run: docker push 140561047603.dkr.ecr.eu-west-2.amazonaws.com/packagebuildert:latest

      # - name: Create Fargate Task
      #   run: aws ecs update-service --cluster my-cluster --service my-service --task-definition task-definition.json
