name: Build and Deploy Docker Image to Amazon ECR and Fargate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev/prod'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    # env:
    #   ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    #   ECR_REPOSITORY: issuepackagebuilder
    #   AWS_REGION: ${{ secrets.AWS_REGION }}
    #   ENVIRONMENT: ${{ github.event.inputs.environment }}
    #   IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      # - name: Install OIDC CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y wget
      #     curl -Lo aws-iam-authenticator https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/aws-iam-authenticator_0.5.9_linux_amd64
      #     curl -Lo aws-iam-authenticator.txt https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.9/authenticator_0.5.9_checksums.txt
      #     awk '/aws-iam-authenticator_0.5.9_linux_amd64/ {print $1}' aws-iam-authenticator.txt
      #     openssl sha1 -sha256 aws-iam-authenticator
      #     chmod +x ./aws-iam-authenticator
      #     mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
      #     echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      #     # sudo mv aws-iam-authenticator /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::140561047603:role/github-action-role
          aws-region: eu-west-2
      - name: Authenticate with ECR
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 140561047603.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker Image
        run: docker build -t packagebuildert:latest .

      - name: Tag Docker Image
        run: docker tag packagebuildert:latest 140561047603.dkr.ecr.us-east-1.amazonaws.com/packagebuildert:latest

      - name: Pus Docker Image
        run: docker push 140561047603.dkr.ecr.eu-west-2.amazonaws.com/packagebuildert:latest

      # - name: Create Fargate Task
      #   run: aws ecs update-service --cluster my-cluster --service my-service --task-definition task-definition.json
