name: Build and Deploy Docker Image to Amazon ECR and Fargate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev/prod'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    # env:
    #   ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
    #   ECR_REPOSITORY: issuepackagebuilder
    #   AWS_REGION: ${{ secrets.AWS_REGION }}
    #   ENVIRONMENT: ${{ github.event.inputs.environment }}
    #   IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      - name: Install Docker
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          apt-cache policy docker-ce
          sudo apt install docker-ce
          sudo systemctl status docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::140561047603:role/github-action-role
          aws-region: eu-west-2
      - name: Authenticate with ECR
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 140561047603.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker Image
        run: docker build -t 140561047603.dkr.ecr.us-east-1.amazonaws.com/packagebuildert:latest .

      # - name: Tag Docker Image
      #   run: docker tag 140561047603.dkr.ecr.us-east-1.amazonaws.com/packagebuildert 140561047603.dkr.ecr.us-east-1.amazonaws.com/packagebuildert:latest

      - name: Push Docker Image
        run: docker push 140561047603.dkr.ecr.eu-west-2.amazonaws.com/packagebuildert:latest

      # - name: Create Fargate Task
      #   run: aws ecs update-service --cluster my-cluster --service my-service --task-definition task-definition.json
